workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_TAG' 

stages:
  - lint
  - test

variables:
  npm_config_cache: ".npm"
  GIT_CLEAN_FLAGS: none

cache:
  paths:
    - node_modules/
    - .npm/

eslint:
  stage: lint
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  script:
    - echo "Running ESlint checks..."
    - npx eslint .

jest-tests:
  stage: test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  script:
    - echo "Stopping other Docker services on device..."
    - docker ps -aq | xargs docker stop || true
    - echo "Starting Docker services..."
    - npm restart
    - echo "Seeding test database..."
    - docker compose run --rm test-db-setup
    - echo "Running test suites..."
    - npm test
    # - npm run test:coverage - Will reenable later
  after_script:
    - docker compose down -v
  timeout: 10 minutes
