###############
# Merge Request Pipeline
#
# On every merge request, builds & runs tests
###############

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

default:
  tags:
    - test

stages:
  - build
  - lint
  - test

variables:
  npm_config_cache: ".npm"
  GIT_CLEAN_FLAGS: none

cache:
  paths:
    - node_modules/
    - .npm/

build:
  stage: build
  script:
    - echo "Pulling Docker images..."
    - docker compose pull
    - echo "Running dependency installation..."
    - docker compose run --rm deps 
  allow_failure: false

lint:
  stage: lint
  script:
    - echo "Running ESlint checks..."
    - npm run lint
  allow_failure: false

test:
  stage: test
  script:
    - echo "Starting Docker services..."
    - docker compose down -v
    - npm run start
    - echo "Running test suites..."
    - npm run test
    # - npm run test:coverage - Will reenable later
  allow_failure: false
